# Generated by Django 3.1.1 on 2020-10-01 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 1, 36, 17, 504574)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 1, 36, 17, 504574)),
        ),
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
